name: build-application
on:
  push: {}
jobs:
  build-application:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "7.0.x"
      - name: Build
        run: dotnet build application
