name: publish-release
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
jobs:
  publish-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "7.0.x"
      - name: Build
        run: dotnet publish application -c Release -o build/linux-amd64 -r linux-x64 -p:PublishReadyToRun=true -p:PublishSingleFile=true -p:PublishTrimmed=true --self-contained true -p:IncludeNativeLibrariesForSelfExtract=true
      - name: Rename
        run: mv build/linux-amd64/application build/linux-amd64/tmg-linux-amd64
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/linux-amd64/tmg-linux-amd64
